name: Package release
on:
  release:
    types: [created]
jobs:
  deploy:
    runs-on: ubuntu-22.04
    defaults:
        run:
          shell: sh

    steps:
      - uses: actions/checkout@v2
      - uses: awalsh128/cache-apt-pkgs-action@latest
        with:
          packages: cmake gcc-arm-none-eabi
          version: 1.0
      - name: Build and run tests
        run: ./build.sh
      - name: Archive production artifacts
        uses: actions/upload-artifact@v3
        with:
          name: dist
          path: |
            dist
      - name: upload binaries to release
        uses: softprops/action-gh-release@v1
        if: ${{startsWith(github.ref, 'refs/tags/') }}
        with:
            files: |
              dist/client-with-usb-host.uf2
              dist/host-1p.uf2
              dist/host-4p.uf2
