name: Package release
on:
  release:
    types: [created]
jobs:
  deploy:
    runs-on: ubuntu-20.04
    defaults:
        run:
          shell: sh

    steps:
      - uses: actions/checkout@v2
      - name: Install prerequisites
        run: sudo apt -y install gcc-arm-none-eabi build-essential
      - name: Install dependencies
        run: git submodule update --recursive --init
      - name: Build main package
        run: ./build.sh
      - name: upload binaries to release
        uses: softprops/action-gh-release@v1
        if: ${{startsWith(github.ref, 'refs/tags/') }}
        with:
            files: |
              dist/client-with-usb-host.uf2
              dist/host-1p.uf2
              dist/host-4p.uf2
