name: Test

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-20.04
    defaults:
        run:
          shell: sh

    steps:
      - uses: actions/checkout@v2
      - name: Install prerequisites
        run: sudo apt -y install gcc-arm-none-eabi build-essential
      - name: Install dependencies
        run: git submodule update --recursive --init
      - name: Build main package
        run: ./build.sh
      - name: Build and run unit tests
        run: ./run_tests.sh
