name: Test

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-22.04
    defaults:
        run:
          shell: sh

    steps:
      - uses: actions/checkout@v2
      - name: Install prerequisites
        run: sudo apt -y install gcc-arm-none-eabi build-essential
      - name: Install dependencies
        run: git submodule update --recursive --init
      - name: Build main package for pico
        run: ./build.sh pico
      - name: Build main package for pico2
        run: ./build.sh pico2 pico2
      - name: Build and run unit tests
        run: ./run_tests.sh
      - name: Save the test build
        uses: actions/upload-artifact@v4
        with:
          name: builds
          path: |
            dist/client-with-usb-host.uf2
            dist/host-1p.uf2
            dist/host-4p.uf2
            dist/pico2_client-with-usb-host.uf2
            dist/pico2_host-1p.uf2
            dist/pico2_host-4p.uf2
