name: Test

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
        run:
          shell: sh

    steps:
      - uses: actions/checkout@v2
      - uses: awalsh128/cache-apt-pkgs-action@latest
        with:
          packages: gcc-arm-none-eabi build-essential
          version: 1.0
      - name: Install prerequisites
        run: git submodule update --recursive --init
      - name: Build main package
        run: ./build.sh
      - name: Build and run unit tests
        run: ./run_tests.sh
